kbyg:
  client-properties:
    client-uuid: "e15cc64f-1266-43bf-9cc5-d979fafa4e34"
    nearby-calculator-delay: 30000
    interface-properties:
      target: "wlan1"
    userPassword: "passwordHere"
  server-properties:
    server-host: "https://kbyg.yakovliam.com/"