kbyg:
  client-properties:
    client-uuid: "00000000-0000-0000-0000-000000000000"
    nearby-calculator-delay: 30000
    interface-properties:
      target: "wlan1"
    userPassword: "passwordHere"
  server-properties:
    server-host: "https://kbyg.yakovliam.com/"